# Generated by Django 4.2.30 on 2026-04-10 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.IntegerField(choices=[(0, 'Mismo día (antes de las 2:00 PM)'), (1, '1 día hábil'), (3, '3–5 días hábiles'), (5, '5–7 días hábiles'), (7, '7–10 días hábiles')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('auto_pdf', models.BooleanField(default=False, help_text='El sistema genera el PDF automáticamente.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('visa', 'Visa / Trámite consular'), ('empleo', 'Empleo / Trabajo'), ('beca', 'Beca / Intercambio'), ('banco', 'Banco / Institución financiera'), ('posgrado', 'Estudios de posgrado'), ('mescyt', 'Beca MESCYT'), ('personal', 'Uso personal'), ('otro', 'Otro')], default='personal', max_length=20)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('es_en', 'Español e Inglés')], default='es', max_length=5)),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institución destinataria')),
                ('observations', models.TextField(blank=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('process', 'En revisión académica'), ('approved', 'Aprobado'), ('ready', 'Listo para retiro'), ('delivered', 'Entregado'), ('rejected', 'Rechazado')], default='pending', max_length=15)),
                ('estimated_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='documents.documenttype')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('icon', models.CharField(default='📋', max_length=5)),
                ('actor', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.documentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
